# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_auto_20190209_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callforcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='callforcontact',
            name='cperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.Person', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='emailaddressforcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='phoneaddressforcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_addresses', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='postaladdressforcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_addresses', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='visitforcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='visitforcontact',
            name='cperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.Person', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='visitforcontact',
            name='ref_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_visits', to='crm.CallForContact', verbose_name='Rif. chiamata'),
        ),
    ]
